config/routes.rb
Rails.application.routes.draw do
  root 'landings#index'
  devise_for :users
  resources :users
  resources :groups do
    resources :bills
  end
end

app/models/group_bill.rb
class GroupBill < ApplicationRecord
  belongs_to :group
  belongs_to :bill
end

app/controllers/group_bills_controller.rb
class GroupBillsController < ApplicationController
  before_action :fetch_group_bill, only: %i[show edit update destroy]

  def index
    @group_bills = GroupBill.all
  end

  def show; end

  def new
    @group_bill = GroupBill.new
  end

  def edit; end

  def create
    @group_bill = GroupBill.new(group_bill_params)

    respond_to do |format|
      if @group_bill.save
        format.html { redirect_to group_bill_url(@group_bill), notice: 'Group bill created successfully.' }
        format.json { render :show, status: :created, location: @group_bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group_bill.update(group_bill_params)
        format.html { redirect_to group_bill_url(@group_bill), notice: 'Group bill updated successfully.' }
        format.json { render :show, status: :ok, location: @group_bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group_bill.destroy

    respond_to do |format|
      format.html { redirect_to group_bills_url, notice: 'Group bill deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private

  def group_bill_params
    params.require(:group_bill).permit(:group_id, :bill_id)
  end

  def fetch_group_bill
    @group_bill = GroupBill.find(params[:id])
  end
end

app/helpers/group_bills_helper.rb
module GroupBillsHelper
end

app/views/group_bills/_form.html.erb
<%= form_with(model: group_bill) do |form| %>
    <% if group_bill.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group_bill.errors.count, "error") %> Group Bill not saved:</h2>
  
        <ul>
          <% group_bill.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :group_id, style: "display: block" %>
      <%= form.text_field :group_id %>
    </div>
  
    <div>
      <%= form.label :bill_id, style: "display: block" %>
      <%= form.text_field :bill_id %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/group_bills/_group_bill.html.erb
<div id="<%= dom_id group_bill %>">
  <p>
    <strong>Group:</strong>
    <%= group_bill.group_id %>
  </p>

  <p>
    <strong>Bill:</strong>
    <%= group_bill.bill_id %>
  </p>
</div>

app/views/group_bills/edit.html.erb
<h1>Group Bills#edit</h1>

<%= render "form", group_bill: @group_bill %>
<br>

<div>
  <%= link_to "Show Group Bill", @group_bill %> |
  <%= link_to "< Group bills List", group_bills_path %>
</div>

app/views/group_bills/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Group Bills</h1>

<div id="group_bills">
  <% @group_bills.each do |group_bill| %>
    <%= render group_bill %>
    <p>
      <%= link_to "Show Group Bill", group_bill %>
    </p>
  <% end %>
</div>

<%= link_to "New Group Bill", new_group_bill_path %>

app/views/group_bills/new.html.erb
<h1>New Group Bill</h1>

<%= render "form", group_bill: @group_bill %>
<br>

<div>
  <%= link_to "< Group Bills List", group_bills_path %>
</div>

app/views/group_bills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_bill %>

<div>
  <%= link_to "Edit Group Bill", edit_group_bill_path(@group_bill) %> |
  <%= link_to "< Group Bills List", group_bills_path %>

  <%= button_to "Delete", @group_bill, method: :delete %>
</div>