config/routes.rb
Rails.application.routes.draw do
  root 'landings#index'
  devise_for :users
  resources :users
  resources :groups do
    resources :bills
  end
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :icon, IconUploader
  has_many :bills, dependent: :destroy
  belongs_to :user

  validates :icon, presence: true
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :fetch_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups.includes(:bills).all.order('id DESC')
    @title = 'Transactions'
  end

  def show
    @group = current_user.groups.includes(:bills).order('id DESC').find(params[:id])
    @title = @group.name
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group created successfully.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_url, notice: 'Group updated successfully.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :description)
  end

  def fetch_group
    @group = Group.find(params[:id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_bill.html.erb
<div class="container-fluid">
<div class="bills">
  <% bills.order('id DESC').each do |bill| %>
    <%= link_to group_bill_path(bill.group_id, bill) do %>
     <div class="mb-3">
      <div class="container-flud mx-2 px-2 bg-white border-bottom">
        <p class="pt-2"><%= bill.name %></p>
        <p class="pb-1 mb-0">Transaction#<%= bill.created_at.to_time.to_i %></p>
        <span class="fa fa-calendar"></span> <span class="mx-1"><%= bill.created_at %></span>
      </div>
      <div class="container-flud mx-2 px-2 bg-white border-bottom">
        <p class="py-2 m-0 d-flex justify-content-between">
        <strong>Payment:</strong>
        $<%= bill.amount %>
        </p>
      </div>
      </div>
      <% end %>
  <% end %>
</div>
</div>

app/views/groups/_form.html.erb
<div class="container mt-4">
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> Group not saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-4">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name:' %>
  </div>

  <div class="form-group mb-4">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon, accept: 'image/png,image/gif,image/jpeg,image/jpg', required: true, class: 'form-control', placeholder: 'Enter' %>
  </div>

  <div class="form-group mb-4">
    <%= form.text_field :description, class: 'form-control', placeholder: 'Enter description:' %>
  </div>
  <div>
    <%= form.submit "Save Category", class: 'btn btn-sm bg-blue col-12 mt-3' %>
  </div>
<% end %>
</div>

app/views/groups/_group.html.erb
<div class="container-fluid">
  <%= link_to group_path(group.id) do %>
  <div class="row d-flex mb-3 bg-white py-1 mx-1 box-card">
     <div class="row-25">
       <img src=<%= group.icon %> alt=<%= group.name %> class="img-fluid img-thumbnail border-0" />
     </div>
     <div class="row-75 px-0 d-flex justify-content-between">
      <div>
       <p class="mb-0 mt-3"><%= group.name %></p>
       <p><%= Date.parse(group.created_at.to_s, '%m-%d-%Y') %></p>
      </div>
      <div class="px-3">
        <strong>$<%= group.bills.inject(0){ |sum, bill| sum + bill.amount } %></strong>
      </div>
     </div>
  </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<% @title = 'Update Group' %>
<%= render "form", group: @group %>
<br>

<div class="px-3">
  <%= link_to "Show Group", @group %> |
  <%= link_to "< Groups List", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>
<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>
<div class="bg-green p-4 w-100 position-fixed bottom-0">
  <%= link_to "Add a new category", new_group_path, class: 'btn bg-green fw-bold col-12 text-uppercase' %>
</div>

app/views/groups/new.html.erb
<% @title = 'New group' %>
<%= render "form", group: @group %>

<br>

<div class="text-center">
  <%= link_to "< Groups List", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="px-3 d-flex justify-content-end mb-4">
  Total: $<%= @group.bills.inject(0){ |sum, bill| sum + bill.amount.to_i } %>
</div>
<%= render @group %>

<div class="container-fluid d-flex mb-4">
<% if can? :update, @group %>
  <%= link_to "Edit Group", edit_group_path(@group), class: 'mx-1' %> |
<% end %>
  <%= link_to "< Groups List", groups_path, class: 'mx-1' %>

<% if can? :destroy, @group %>
  | <%= button_to "Delete", @group, method: :delete, class: 'mx-1 border-0 text-primary' %>
<% end %>
</div>

<%= render 'bill', bills: @group.bills %>

<div class="bg-green p-3 w-100 position-fixed bottom-0">
  <%= link_to "add a new transaction", new_group_bill_path(@group.id), class: 'btn bg-green fw-bold col-12 text-uppercase' %>
</div>