config/routes.rb
Rails.application.routes.draw do
  root 'landings#index'
  devise_for :users
  resources :users
  resources :groups do
    resources :bills
  end
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 0 }
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[show edit update destroy]

  def index
    @bills = current_user.bills.all
  end

  def show
    @bill = current_user.bills.find(params[:id])
  end

  def new
    @bill = Bill.new
    @group_id = params[:group_id]
  end

  def edit; end

  def create
    @bill = current_user.bills.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to group_path(@bill.group_id), notice: 'Bill created successfully.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to group_path(@bill.group_id), notice: 'Bill updated successfully.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to group_url(params[:group_id]), notice: 'Bill deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:name, :amount, :group_id, :description)
  end

  def set_bill
    @bill = Bill.find(params[:id])
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill.html.erb
<% @title = bill.name %>
<div class="container-flud mx-3 px-2 bg-white border-bottom">
  <p class="py-2">Transaction#<%= bill.created_at.to_time.to_i %> <br/>
   <span class="fa fa-calendar"></span> <span class="mx-1"><%= bill.created_at %></span>
  </p>
</div>
<div class="container-flud mx-3 px-2 bg-white border-bottom">
  <p class="py-2 m-0 d-flex justify-content-between">
    <strong>payment:</strong>
    $<%= bill.amount %>
  </p>
</div>

app/views/bills/_form.html.erb
<%= form_with(model: bill, url: group_bills_path) do |form| %>
    <% if bill.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(bill.errors.count, "error") %> Bill not saved:</h2>
  
        <ul>
          <% bill.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= form.text_field :name, class: 'form-control my-3', placeholder: 'Enter name:' %>
    </div>
  
    <div class="form-group">
      <%= form.text_field :amount, class: 'form-control my-3', placeholder: 'Enter amount:' %>
      <%= form.hidden_field :group_id, {value: @group_id} %>
    </div>
  
    <div class="form-group">
      <%= form.text_area :description, class: 'form-control my-3', placeholder: 'Add description:' %>
    </div>
  
    <div class="form-group">
      <%= form.submit 'Save', class: 'btn btn-primary btn-sm bg-blue col-12' %>
    </div>
  <% end %>
  

app/views/bills/edit.html.erb
<h1>Bills#edit</h1>

<%= render "form", bill: @bill %>
<br>

<div>
  <%= link_to "Show Bill", @bill %> |
  <%= link_to "< Bills List", bills_path %>
</div>

app/views/bills/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bills#index</h1>

<div id="bills">
  <% @bills.each do |bill| %>
    <%= render bill %>
    <p>
      <%= link_to "Show Bill", group_bill_path(bill.group_id, bill) %>
    </p>
  <% end %>
</div>

app/views/bills/new.html.erb
<% @title = 'Add New Bill' %>
<div class="container-fluid">
  <div class="row">
    <%= render "form", bill: @bill, group_id: @group_id %>
  </div>
</div>

app/views/bills/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container-flud d-flex mx-3 bg-white p-3">
  <div>
    <img src=<%= @bill.group.icon %> alt=<%= @bill.group.name %> class="img-fluid img-thumbnail border-0" width="100px" />
  </div>
  <div>
    <p class="mx-2"><%= @bill.name %></p>
  </div>
</div>
<div class="container-flud d-flex mx-3 bg-white p-3 border-bottom">
  <p class="mx-2"><%= @bill.description %></p>
</div>

<%= render @bill %>

<div class="container-fluid d-flex mt-3">
  <%= link_to "< Bills List", group_path(@bill.group_id), class: '' %>
<% if can? :destroy, @bill %>
<div class="mx-2">|</div> <%= button_to "Delete Bill", group_bill_path(@bill.group_id, @bill), method: :delete, class: 'border-0 text-primary' %>
<% end %>
</div>